// src/components/LaunchCodesScreen.js
// ─────────────────────────────────────────────────────────────
// Shown to the organizer immediately after launching a league.
// Loads player codes via the get_player_codes RPC so that
// session_token is never stored in the shared participants array.
// ─────────────────────────────────────────────────────────────

import React, { useState, useEffect } from 'react';
import ThemeToggle from './shared/ThemeToggle';
import { fetchPlayerCodes } from '../lib/db';

function CopyButton({ text, label = 'Copy' }) {
  const [copied, setCopied] = useState(false);
  const handle = () => {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };
  return (
    <button className="code-copy-btn" onClick={handle}>
      {copied ? '✓ Copied' : label}
    </button>
  );
}

function PlayerCodeRow({ player, leagueName, leagueUrl }) {
  const token = player.session_token || '—';
  const invite = `Hi ${player.name}! You've been added to ${leagueName || 'a Ladder League'}. Open ${leagueUrl} and enter your code: ${token}`;

  return (
    <div className="launch-code-row">
      <div className="launch-code-player">
        <span className="launch-code-name">{player.name}</span>
        {player.role === 'admin' && (
          <span className="launch-code-rating">Admin</span>
        )}
      </div>
      <code className="launch-code-token">{token}</code>
      <div className="launch-code-actions">
        <CopyButton text={token} label="Copy code" />
        <CopyButton text={invite} label="Copy invite message" />
      </div>
    </div>
  );
}

// Props:
//   leagueId        — real UUID from effectiveSettings.id (required for DB lookup)
//   leagueName      — display name
//   isDoubles       — unused for code display; retained for future use
//   onEnterDashboard — callback when organizer is done
function LaunchCodesScreen({ leagueId, leagueName, isDoubles, onEnterDashboard }) {
  const leagueUrl = window.location.href;
  const isOffline = !leagueId || String(leagueId).startsWith('local-');

  const [playerCodes, setPlayerCodes] = useState([]);
  const [loadingCodes, setLoadingCodes] = useState(!isOffline);
  const [codesError, setCodesError] = useState(null);

  useEffect(() => {
    if (isOffline) return;
    fetchPlayerCodes(leagueId)
      .then(setPlayerCodes)
      .catch((err) => {
        console.warn('[LaunchCodesScreen] failed to load codes:', err.message);
        setCodesError('Could not load player codes. Refresh the page or check your connection.');
      })
      .finally(() => setLoadingCodes(false));
  }, [leagueId, isOffline]);

  const allCodes = playerCodes
    .map((p) => `${p.name}: ${p.session_token || '—'}`)
    .join('\n');

  const allInvites = playerCodes
    .map(
      (p) =>
        `Hi ${p.name}! Open ${leagueUrl} and enter your code: ${p.session_token || '—'}`,
    )
    .join('\n\n');

  return (
    <div className="wizard-card wizard-card-wide">
      <div className="card-accent" />

      <div className="card-header">
        <div className="card-header-top">
          <div>
            <div className="brand">Ladder League</div>
            <div className="step-indicator">
              League Created — Share Player Codes
            </div>
          </div>
          <ThemeToggle />
        </div>
      </div>

      <div className="card-body">
        <div className="launch-codes-hero">
          <div className="launch-codes-check">✓</div>
          <div className="launch-codes-title">{leagueName} is live.</div>
          <div className="launch-codes-subtitle">
            Share each player's code with them so they can log in. Players open
            this URL and enter their code to access the league.
          </div>
          <div className="launch-codes-url">{leagueUrl}</div>
        </div>

        {isOffline ? (
          <div className="info-box" style={{ marginTop: 16 }}>
            <div>
              <div style={{ fontWeight: 600, marginBottom: 3 }}>
                Offline mode — codes unavailable
              </div>
              Player codes are generated by the server and can only be
              retrieved when connected to Supabase. Re-open this league
              after reconnecting to find codes in the Players panel.
            </div>
          </div>
        ) : loadingCodes ? (
          <div className="launch-codes-list" style={{ textAlign: 'center', padding: '24px 0', color: 'var(--color-muted)' }}>
            Loading codes…
          </div>
        ) : codesError ? (
          <div className="picker-error" role="alert">
            ⚠ {codesError}
          </div>
        ) : (
          <>
            <div className="launch-codes-toolbar">
              <span className="launch-codes-count">
                {playerCodes.length} players
              </span>
              <div style={{ display: 'flex', gap: '8px' }}>
                <CopyButton text={allCodes} label="Copy all codes" />
                <CopyButton text={allInvites} label="Copy all invites" />
              </div>
            </div>

            <div className="launch-codes-list">
              {playerCodes.map((p) => (
                <PlayerCodeRow
                  key={p.id}
                  player={p}
                  leagueName={leagueName}
                  leagueUrl={leagueUrl}
                />
              ))}
            </div>

            <div className="launch-codes-tip">
              💡 Save these codes now — you can find them again anytime from
              the <strong>Players</strong> button in the dashboard.
            </div>
          </>
        )}
      </div>

      <div className="card-footer">
        <button className="btn-next btn-launch" onClick={onEnterDashboard}>
          Enter Dashboard →
        </button>
      </div>
    </div>
  );
}

export default LaunchCodesScreen;
